package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.listing.domain.RuleConstants;
import java.util.Arrays;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;



rule "Command - API - Action - listing.command.send-case-for-listing"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.send-case-for-listing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.CROWN_COURT_ADMIN));
  then
    $outcome.setSuccess(true);
end


rule "Command - API - Action - listing.command.update-hearing-for-listing"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.update-hearing-for-listing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS));
  then
    $outcome.setSuccess(true);
end

