package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;


rule "Command - API - Action - listing.command.send-case-for-listing"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.send-case-for-listing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Crown Court Admin"));
  then
    $outcome.setSuccess(true);
end

