package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.listing.domain.RuleConstants;
import java.util.Arrays;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;



rule "Command - API - Action - listing.command.list-court-hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.list-court-hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.LEGAL_ADVISERS,
    RuleConstants.COURT_CLERKS, RuleConstants.SYSTEM_USERS));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - listing.command.update-hearing-for-listing"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.update-hearing-for-listing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS, RuleConstants.COURT_ASSOCIATE));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - listing.command.extend-hearing-for-hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.extend-hearing-for-hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS, RuleConstants.COURT_ASSOCIATE));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - listing.command.change-judiciary-for-hearings"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.change-judiciary-for-hearings");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS, RuleConstants.COURT_ASSOCIATE));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - listing.command.sequence-hearings"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.sequence-hearings");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS, RuleConstants.CPS, RuleConstants.YOTS, RuleConstants.NPS, RuleConstants.COURT_ASSOCIATE, RuleConstants.GROUP_POLICE_ADMIN, RuleConstants.GROUP_VICTIMS_WITNESS_CARE_ADMIN));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - listing.command.restrict-court-list"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.restrict-court-list");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS, RuleConstants.CPS, RuleConstants.YOTS, RuleConstants.NPS));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - listing.command.publish-court-list"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.publish-court-list");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - listing.command.publish-court-lists-for-crown-courts"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.publish-court-lists-for-crown-courts");
    eval(userAndGroupProvider.isSystemUser($action))
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - listing.command.court-list-request-export"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.command.court-list-request-export");
    eval(userAndGroupProvider.isSystemUser($action))
  then
    $outcome.setSuccess(true);
end

