package uk.gov.moj.cpp.listing.event.processor.xhibit;

import static java.time.ZonedDateTime.parse;
import static java.util.UUID.randomUUID;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
import static org.mockito.Matchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import uk.gov.justice.services.fileservice.api.FileStorer;
import uk.gov.moj.cpp.listing.event.processor.xhibit.courtlist.CourtListMetadata;

import java.io.InputStream;
import java.util.UUID;

import javax.json.JsonObject;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;
import org.slf4j.Logger;

@RunWith(MockitoJUnitRunner.class)
public class FileServiceClientTest {

    @Captor
    private ArgumentCaptor<JsonObject> fileServiceMetadataCaptor;
    @Captor
    private ArgumentCaptor<InputStream> fileContentStreamCaptor;
    @InjectMocks
    private FileServiceClient fileServiceClient;
    @Mock
    private FileStorer fileStorer;
    @Mock
    private Logger logger;

    @Test
    public void shouldStoreFileUsingMetadata() throws Exception {

        // Method parameters
        final CourtListMetadata courtListMetadata = new CourtListMetadata("TESTFILENAME",
                "UNIQUEID", parse("2018-01-02T13:04:05+00:00[Europe/London]"));
        final InputStream expectedFileContentStream = mock(InputStream.class);

        // Id generated by file service
        final UUID expectedFileId = randomUUID();
        when(fileStorer.store(any(), any())).thenReturn(expectedFileId);

        final UUID actualFileId = fileServiceClient.store(courtListMetadata, expectedFileContentStream);

        verify(fileStorer).store(fileServiceMetadataCaptor.capture(), fileContentStreamCaptor.capture());

        assertThat("UUID generated by fileStorer", actualFileId, is(expectedFileId));
        assertThat(fileContentStreamCaptor.getValue(), is(expectedFileContentStream));
        assertThat(fileServiceMetadataCaptor.getValue().getString("filename"), is(courtListMetadata.getFilename()));
        assertThat(fileServiceMetadataCaptor.getValue().getString("documentUniqueId"), is(courtListMetadata.getDocumentUniqueId()));
    }
}
