package uk.gov.moj.cpp.listing.persistence.repository;

import uk.gov.justice.services.common.util.UtcClock;
import uk.gov.moj.cpp.listing.domain.JurisdictionType;
import uk.gov.moj.cpp.listing.domain.Type;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.Month;
import java.time.ZonedDateTime;
import java.util.UUID;

import static java.lang.Boolean.FALSE;
import static java.lang.Boolean.TRUE;
import static java.time.LocalDate.now;
import static java.time.ZoneOffset.UTC;
import static java.util.UUID.fromString;
import static java.util.UUID.randomUUID;
import static uk.gov.justice.services.test.utils.core.random.RandomGenerator.BOOLEAN;
import static uk.gov.moj.cpp.listing.domain.JurisdictionType.CROWN;
import static uk.gov.moj.cpp.listing.domain.JurisdictionType.MAGISTRATES;
import static uk.gov.moj.cpp.listing.domain.Type.type;

public interface PersistenceTestsInt {
    UtcClock UTC_CLOCK = new UtcClock();
    Boolean ALLOCATED = TRUE;
    Boolean UNALLOCATED = FALSE;
    Boolean IS_POSSIBLE_DISQUALIFICATION = FALSE;
    Boolean RANDOM_ALLOCATED = BOOLEAN.next();
    Boolean NOT_VACATED = FALSE;
    String UNALLOCATED_STR = "false";
    UUID HEARING_ID = randomUUID();
    UUID OTHER_HEARING_ID = randomUUID();
    UUID OTHER_HEARING_ID2 = randomUUID();
    UUID VACATED_HEARING_ID = randomUUID();
    UUID COURT_ROOM_ID = randomUUID();
    UUID COURT_CENTRE_ID = randomUUID();
    UUID OTHER_COURT_CENTRE_ID = randomUUID();
    UUID AUTHORITY_ID = randomUUID();
    UUID OTHER_AUTHORITY_ID = randomUUID();
    UUID TYPE_OF_LIST_ID = randomUUID();
    Type HEARING_TYPE = type().withId(fromString("bf8155e1-90b9-4080-b133-bfbad895d6e4")).withDescription("TRIAL").build();
    Type OTHER_HEARING_TYPE = type().withId(randomUUID()).withDescription("SENTENCE").build();
    JurisdictionType JURISDICTION_TYPE = CROWN;
    String JUDICIAL_ID = "0ab98bfb-fc34-44c4-a573-3801343cf123";
    String OTHER_JUDICIAL_ID = "a666923b-bbc1-4ed7-b340-c72f9341035b";
    JurisdictionType OTHER_JURISDICTION_TYPE = MAGISTRATES;
    LocalDate START_SEARCH_DATE = now();
    LocalDate END_SEARCH_DATE = now().plusDays(1);
    LocalDate START_DATE = now();
    LocalDate END_DATE = now().plusDays(2);
    LocalDate WEEK_COMMENCING_START_DATE = now();
    LocalDate WEEK_COMMENCING_END_DATE = now().plusDays(7);
    ZonedDateTime START_TIME = UTC_CLOCK.now();
    ZonedDateTime END_TIME = UTC_CLOCK.now().plusHours(2);
    ZonedDateTime EARLIEST_SEARCH_DATE_TIME = ZonedDateTime.of(START_SEARCH_DATE, LocalTime.MIN, UTC);
    ZonedDateTime LATEST_SEARCH_DATE_TIME = ZonedDateTime.of(START_SEARCH_DATE, LocalTime.MAX, UTC);
    ZonedDateTime HEARING_DATE = UTC_CLOCK.now();
    ZonedDateTime DAY_1_HEARING_DATE = UTC_CLOCK.now();
    ZonedDateTime DAY_2_HEARING_DATE = UTC_CLOCK.now();
    ZonedDateTime DAY_3_HEARING_DATE = UTC_CLOCK.now();
    ZonedDateTime DAY_1_START_TIME = UTC_CLOCK.now();
    ZonedDateTime DAY_1_END_TIME = DAY_1_START_TIME.plusHours(2);
    ZonedDateTime DAY_2_START_TIME = DAY_1_START_TIME.plusDays(1);
    ZonedDateTime DAY_2_END_TIME = DAY_2_START_TIME.plusHours(2);
    ZonedDateTime DAY_3_START_TIME = DAY_1_START_TIME.plusDays(2);
    ZonedDateTime DAY_3_END_TIME = DAY_3_START_TIME.plusHours(2);
    UUID LISTED_CASES_ID_1 = fromString("cd2a5c26-d2fd-40b3-a8be-6f1e578c5034");
    UUID COURT_APPLICATION_ID_1 = fromString("a549f16a-100d-4dca-b206-1454947e20bb");
    UUID LISTED_CASES_ID_2 = fromString("563d479b-7483-4216-9f13-aef8d87d68ae");
    UUID COURT_APPLICATION_ID_2 = fromString("ce15d9e1-c8ee-44ae-8f28-45d3d8286518");
    Boolean UNSCHEDULED = FALSE;
    String HEARING_ID_FIELD = "HEARING_ID_FIELD";
    String JURISDICTION_TYPE_FIELD = "JURISDICTION_TYPE_FIELD";
    String JUDICIAL_ID_FIELD = "JUDICIAL_ID";
    String ALLOCATED_FIELD = "ALLOCATED_FIELD";
    String VACATED_TRIAL_FIELD = "VACATED_TRIAL_FIELD";
    String COURT_CENTRE_ID_FIELD = "COURT_CENTRE_ID_FIELD";
    String COURT_ROOM_ID_FIELD = "COURT_ROOM_ID_FIELD";
    String AUTHORITY_ID_FIELD = "AUTHORITY_ID_FIELD";
    String HEARING_TYPE_DESCRIPTION_FIELD = "HEARING_TYPE_DESCRIPTION_FIELD";
    String HEARING_TYPE_ID_FIELD = "HEARING_TYPE_ID_FIELD";
    String START_DATE_FIELD = "START_DATE_FIELD";
    String END_DATE_FIELD = "END_DATE_FIELD";
    String WEEK_COMMENCING_START_FIELD = "WEEK_COMMENCING_START_FIELD";
    String WEEK_COMMENCING_END_FIELD = "WEEK_COMMENCING_END_FIELD";
    String START_TIME_FIELD = "START_TIME_FIELD";
    String END_TIME_FIELD = "END_TIME_FIELD";
    String HEARING_DATE_FIELD = "HEARING_DATE_FIELD";
    String FIELD_2_HEARING_DATE = "FIELD_2_HEARING_DATE";
    String CASE_REFERENCE = "45DI277164";
    String MASTER_DEFENDANT_ID = "e2b13dc1-de95-11e8-9df5-e56feb0784f6";
    String LINKED_CASE_URN = "45DI277164";
    String EMPTY_STRING = "";
    String DAY_1_HEARING_DATE_FIELD = "DAY_1_HEARING_DATE_FIELD";
    String DAY_2_HEARING_DATE_FIELD = "DAY_2_HEARING_DATE_FIELD";
    String DAY_3_HEARING_DATE_FIELD = "DAY_3_HEARING_DATE_FIELD";
    String DAY_1_START_TIME_FIELD = "DAY_1_START_TIME_FIELD";
    String DAY_1_END_TIME_FIELD = "DAY_1_END_TIME_FIELD";
    String DAY_2_START_TIME_FIELD = "DAY_2_START_TIME_FIELD";
    String DAY_2_END_TIME_FIELD = "DAY_2_END_TIME_FIELD";
    String DAY_3_START_TIME_FIELD = "DAY_3_START_TIME_FIELD";
    String DAY_3_END_TIME_FIELD = "DAY_3_END_TIME_FIELD";
    String DAY_1_IS_CANCELLED_FIELD = "DAY_1_IS_CANCELLED_FIELD";
    String DAY_2_IS_CANCELLED_FIELD = "DAY_2_IS_CANCELLED_FIELD";
    String DAY_3_IS_CANCELLED_FIELD = "DAY_3_IS_CANCELLED_FIELD";
    String TEST_DATA_SAMPLE_HEARING_JSON = "test-data/sample-hearing.json";
    String TEST_DATA_SAMPLE_HEARING_NULL_VACATED_JSON = "test-data/sample-hearing-null-vacated.json";
    String TEST_DATA_SAMPLE_UNSCHEDULED_HEARING_JSON = "test-data/sample-unscheduled-hearing.json";
    String TEST_DATA_SAMPLE_UNSCHEDULED_WITHOUT_CASE_HEARING_JSON = "test-data/sample-unscheduled-hearing-without-case.json";
    String TEST_DATA_SAMPLE_MULTIDAY_HEARING_JSON = "test-data/sample-multiday-hearing.json";
    String SAMPLE_UNALLOCATED_HEARING_FOR_WEEK_COMMENCING = "test-data/sample-unallocated-hearing-for-week-commencing.json";
    String TEST_DATA_SAMPLE_HEARING_WITH_COURT_CENTRE_JSON = "test-data/hearing-with-court-centre-details.json";
    String EARLIEST_SEARCH_DATE = "1900-01-01";
    String LATEST_SEARCH_DATE = "9999-01-01";
    // PublishedCourtListRepositoryTest start
    UUID COURT_CENTRE_ID_ONE = UUID.fromString("247da57c-d739-4b88-ac16-0feaf8a59833");
    UUID COURT_CENTRE_ID_TWO = UUID.fromString("d7a89a94-f6e9-40d5-804e-ded5626b474e");
    LocalDate APRIL_FOOLS_DAY_2020 = LocalDate.of(2020, Month.APRIL, 1);
    LocalDate BOXING_DAY_2020 = LocalDate.of(2020, Month.DECEMBER, 26);
    ZonedDateTime LAST_UPDATED = ZonedDateTime.now();
    ZonedDateTime LAST_EXPORTED = ZonedDateTime.now();
    UUID courtListId = UUID.randomUUID();
}
