#%RAML 0.8
title: Listing - Command Handler
baseUri: message://command/handler/message/listing

/listing.handler.command:
  post:
    body:
      application/vnd.listing.command.list-court-hearing-enriched+json:
        example: !include json/listing.command.list-court-hearing-enriched.json
        schema:  !include json/schema/listing.command.list-court-hearing-enriched.json

      application/vnd.listing.command.update-hearing-for-listing-enriched+json:
        example: !include json/listing.command.update-hearing-for-listing-enriched.json
        schema: !include json/schema/listing.command.update-hearing-for-listing-enriched.json

      application/vnd.listing.command.update-case-defendant-details+json:
        schema: !include json/schema/listing.command.update-case-defendant-details.json
        example: !include json/listing.command.update-case-defendant-details.json

      application/vnd.listing.command.update-case-defendant-offences+json:
        schema: !include json/schema/listing.command.update-case-defendant-offences.json
        example: !include json/listing.command.update-case-defendant-offences.json

      application/vnd.listing.command.update-defendants-for-hearing+json:
        schema: !include json/schema/listing.command.update-defendants-for-hearing.json
        example: !include json/listing.command.update-defendants-for-hearing.json

      application/vnd.listing.command.update-offences-for-hearing+json:
        schema: !include json/schema/listing.command.update-offences-for-hearing.json
        example: !include json/listing.command.update-offences-for-hearing.json

      application/vnd.listing.command.delete-offences-for-hearing+json:
        schema: !include json/schema/listing.command.delete-offences-for-hearing.json
        example: !include json/listing.command.delete-offences-for-hearing.json

      application/vnd.listing.command.add-hearing-to-case+json:
        schema: !include json/schema/listing.command.add-hearing-to-case.json
        example: !include json/listing.command.add-hearing-to-case.json

      application/vnd.listing.command.add-offences-for-hearing+json:
        schema: !include json/schema/listing.command.add-offences-for-hearing.json
        example: !include json/listing.command.add-offences-for-hearing.json

      application/vnd.listing.command.change-judiciary-for-hearings+json:
        schema: !include json/schema/listing.command.change-judiciary-for-hearings.json
        example: !include json/listing.command.change-judiciary-for-hearings.json

      application/vnd.listing.command.sequence-hearings+json:
        schema: !include json/schema/listing.command.sequence-hearings.json
        example: !include json/listing.command.sequence-hearings.json

      application/vnd.listing.command.update-court-application-for-hearings+json:
        schema: !include json/schema/listing.command.update-court-application-for-hearings.json
        example: !include json/listing.command.update-court-application-for-hearings.json

      application/vnd.listing.command.add-court-application-for-hearing+json:
        schema: !include json/schema/listing.command.add-court-application-for-hearing.json
        example: !include json/listing.command.add-court-application-for-hearing.json

      application/vnd.listing.command.add-defendants-to-court-proceedings+json:
        schema: !include json/schema/listing.command.add-defendants-to-court-proceedings.json
        example: !include json/listing.command.add-defendants-to-court-proceedings.json

      application/vnd.listing.command.add-court-application-to-hearing+json:
        schema: !include json/schema/listing.command.add-court-application-to-hearing.json
        example: !include json/listing.command.add-court-application-to-hearing.json

      application/vnd.listing.command.update-court-application+json:
        schema: !include json/schema/listing.command.update-court-application.json
        example: !include json/listing.command.update-court-application.json

      application/vnd.listing.command.add-defendants-to-court-proceedings-for-hearing+json:
        schema: !include json/schema/listing.command.add-defendants-to-court-proceedings-for-hearing.json
        example: !include json/listing.command.add-defendants-to-court-proceedings-for-hearing.json

      application/vnd.listing.command.restrict-court-list+json:
        schema: !include json/schema/listing.command.restrict-court-list.json
        example: !include json/listing.command.restrict-court-list.json

      application/vnd.listing.command.eject-case-or-application+json:
        schema: !include json/schema/listing.command.eject-case-or-application.json
        example: !include json/listing.command.eject-case-or-application.json

      application/vnd.listing.command.record-court-list-export-successful+json:
        schema: !include json/schema/listing.command.record-court-list-export-successful.json
        example: !include json/listing.command.record-court-list-export-successful.json

      application/vnd.listing.command.record-court-list-export-failed+json:
        schema: !include json/schema/listing.command.record-court-list-export-failed.json
        example: !include json/listing.command.record-court-list-export-failed.json

      application/vnd.listing.command.publish-court-list+json:
        schema: !include json/schema/listing.command.publish-court-list.json
        example: !include json/listing.command.publish-court-list.json