#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/listener/message/listing

/listing.event:
  post:
    body:

      application/vnd.listing.events.hearing-listed+json:
        example: !include json/listing.events.hearing-listed.json
        schema: !include json/schema/listing.events.hearing-listed.json

      application/vnd.listing.events.court-centre-changed-for-hearing+json:
        example: !include json/listing.events.court-centre-changed-for-hearing.json
        schema: !include json/schema/listing.events.court-centre-changed-for-hearing.json

      application/vnd.listing.events.court-room-assigned-to-hearing+json:
        example: !include json/listing.events.court-room-assigned-to-hearing.json
        schema: !include json/schema/listing.events.court-room-assigned-to-hearing.json

      application/vnd.listing.events.court-room-changed-for-hearing+json:
        example: !include json/listing.events.court-room-changed-for-hearing.json
        schema: !include json/schema/listing.events.court-room-changed-for-hearing.json

      application/vnd.listing.events.court-room-removed-from-hearing+json:
        example: !include json/listing.events.court-room-removed-from-hearing.json
        schema: !include json/schema/listing.events.court-room-removed-from-hearing.json

      application/vnd.listing.events.hearing-days-changed-for-hearing+json:
        example: !include json/listing.events.hearing-days-changed-for-hearing.json
        schema: !include json/schema/listing.events.hearing-days-changed-for-hearing.json

      application/vnd.listing.events.judiciary-assigned-to-hearing+json:
        example: !include json/listing.events.judiciary-assigned-to-hearing.json
        schema: !include json/schema/listing.events.judiciary-assigned-to-hearing.json

      application/vnd.listing.events.jurisdiction-changed-for-hearing+json:
        example: !include json/listing.events.jurisdiction-changed-for-hearing.json
        schema: !include json/schema/listing.events.jurisdiction-changed-for-hearing.json

      application/vnd.listing.events.judiciary-changed-for-hearing+json:
        example: !include json/listing.events.judiciary-changed-for-hearing.json
        schema: !include json/schema/listing.events.judiciary-changed-for-hearing.json

      application/vnd.listing.events.judiciary-removed-from-hearing+json:
        example: !include json/listing.events.judiciary-removed-from-hearing.json
        schema: !include json/schema/listing.events.judiciary-removed-from-hearing.json

      application/vnd.listing.events.non-sitting-days-assigned-to-hearing+json:
        example: !include json/listing.events.non-sitting-days-assigned-to-hearing.json
        schema: !include json/schema/listing.events.non-sitting-days-assigned-to-hearing.json

      application/vnd.listing.events.non-sitting-days-changed-for-hearing+json:
        example: !include json/listing.events.non-sitting-days-changed-for-hearing.json
        schema: !include json/schema/listing.events.non-sitting-days-changed-for-hearing.json

      application/vnd.listing.events.non-default-days-assigned-to-hearing+json:
        example: !include json/listing.events.non-default-days-assigned-to-hearing.json
        schema: !include json/schema/listing.events.non-default-days-assigned-to-hearing.json

      application/vnd.listing.events.non-default-days-changed-for-hearing+json:
        example: !include json/listing.events.non-default-days-changed-for-hearing.json
        schema: !include json/schema/listing.events.non-default-days-changed-for-hearing.json

      application/vnd.listing.events.start-date-changed-for-hearing+json:
        example: !include json/listing.events.start-date-changed-for-hearing.json
        schema: !include json/schema/listing.events.start-date-changed-for-hearing.json

      application/vnd.listing.events.end-date-changed-for-hearing+json:
        example: !include json/listing.events.end-date-changed-for-hearing.json
        schema: !include json/schema/listing.events.end-date-changed-for-hearing.json

      application/vnd.listing.events.type-changed-for-hearing+json:
        example: !include json/listing.events.type-changed-for-hearing.json
        schema: !include json/schema/listing.events.type-changed-for-hearing.json

      application/vnd.listing.events.hearing-allocated-for-listing+json:
        example: !include json/listing.events.hearing-allocated-for-listing.json
        schema: !include json/schema/listing.events.hearing-allocated-for-listing.json

      application/vnd.listing.events.hearing-unallocated-for-listing+json:
        example: !include json/listing.events.hearing-unallocated-for-listing.json
        schema: !include json/schema/listing.events.hearing-unallocated-for-listing.json

      application/vnd.listing.events.hearing-language-changed-for-hearing+json:
        example: !include json/listing.events.hearing-language-changed-for-hearing.json
        schema: !include json/schema/listing.events.hearing-language-changed-for-hearing.json

      application/vnd.listing.events.new-defendant-details-updated+json:
        schema: !include json/schema/listing.events.new-defendant-details-updated.json
        example: !include json/listing.events.new-defendant-details-updated.json

      application/vnd.listing.events.offence-added+json:
        schema: !include json/schema/listing.events.offence-added.json
        example: !include json/listing.events.offence-added.json

      application/vnd.listing.events.offence-updated+json:
        schema: !include json/schema/listing.events.offence-updated.json
        example: !include json/listing.events.offence-updated.json

      application/vnd.listing.events.offence-deleted+json:
        schema: !include json/schema/listing.events.offence-deleted.json
        example: !include json/listing.events.offence-deleted.json

      application/vnd.listing.events.hearing-days-sequenced+json:
        schema: !include json/schema/listing.events.hearing-days-sequenced.json
        example: !include json/listing.events.hearing-days-sequenced.json

      application/vnd.listing.events.court-application-updated-for-hearing+json:
        schema: !include json/schema/listing.events.court-application-updated-for-hearing.json
        example: !include json/listing.events.court-application-updated-for-hearing.json

      application/vnd.listing.events.court-application-added-for-hearing+json:
        schema: !include json/schema/listing.events.court-application-added-for-hearing.json
        example: !include json/listing.events.court-application-added-for-hearing.json

      application/vnd.listing.events.new-defendant-added-for-court-proceedings+json:
        schema: !include json/schema/listing.events.new-defendant-added-for-court-proceedings.json
        example: !include json/listing.events.new-defendant-added-for-court-proceedings.json

      application/vnd.listing.events.court-list-restricted+json:
        schema: !include json/schema/listing.events.court-list-restricted.json
        example: !include json/listing.events.court-list-restricted.json

      application/vnd.listing.events.case-ejected+json:
        schema: !include json/schema/listing.events.case-ejected.json
        example: !include json/listing.events.case-ejected.json

      application/vnd.listing.events.application-ejected+json:
        schema: !include json/schema/listing.events.application-ejected.json
        example: !include json/listing.events.application-ejected.json
