#%RAML 0.8
title: Listing Query API
baseUri: http://localhost:8080/listing-query-view/query/view/rest/listing
protocols: [ HTTP, HTTPS ]

/hearings:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.listing.search.hearings+json
            name: listing.search.hearings
        ...
      queryParameters:
        allocated:
          description: true for allocated hearings, false for unallocated hearings
          type: boolean
          required: true
        courtCentreId:
          description: reference data id for the court centre
          type: string
          required: true


      responses:
            200:
                description: OK
                body:
                  application/vnd.listing.search.hearings+json:
                    example:  !include json/listing.search.hearings.json
                    schema:  !include  json/schema/listing.search.hearings.json


