changeLogFile: liquibase/listing-view-store-db-changelog.xml
strict=false
driver: org.postgresql.Driver
url: jdbc:postgresql://localhost:5432/listingviewstore
username: listing
password: listing
verbose: true
dropFirst: false
