package uk.gov.moj.cpp.listing.event.processor.xhibit.courtlist.mapper;

import uk.gov.moj.cpp.listing.domain.xhibit.generated.ObjectFactory;
import uk.gov.moj.cpp.listing.event.processor.xhibit.courtlist.CourtListGenerationContext;

import javax.json.JsonObject;
import javax.xml.bind.JAXBElement;

public abstract class AbstractCourtListMapper {

    protected static final ObjectFactory objectFactory = new ObjectFactory();

    protected JsonObject courtListForPublishing;

    protected CourtServicesMapper courtServicesMapper;

    protected CourtListGenerationContext context;

    public AbstractCourtListMapper(final CourtListGenerationContext context, final JsonObject courtListForPublishing,
                          final CourtServicesMapper courtServicesMapper) {
        this.context = context;
        this.courtListForPublishing = courtListForPublishing;
        this.courtServicesMapper = courtServicesMapper;
    }

    @SuppressWarnings({"squid:S1452"})  // Cannot remove usage of generic wildcard type, since structure classes are generated by JAXB without ancestors.
    public abstract JAXBElement<?> generate();
}
