#%RAML 0.8
title: Listing Query API
baseUri: http://localhost:8080/listing-query-api/query/api/rest/listing
protocols: [ HTTP, HTTPS ]

/hearings:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.listing.search.hearings+json
            name: listing.search.hearings
        ...
      queryParameters:
        allocated:
          description: true for allocated hearings, false for unallocated hearings
          type: boolean
          required: true
        courtCentreId:
          description: reference data id for the court centre
          type: string
          required: false
        courtRoomId:
          description: reference data id for the court room
          type: string
          required: false
        authorityId:
          description: reference data id for the authority code
          type: string
          required: false
        hearingTypeId:
          description: reference data id for the hearng type
          type: string
          required: false
        jurisdictionType:
          description: the jurisdiction under which the hearing is being prosecuted, for example CROWN or MAGISTRATE
          type: string
          required: false
        searchDate:
          description: Search for hearings where the searchDate parameter is between the start and end date of the hearing.
          type: date
          required: true
        startTime:
          description: e.g. '10:30'. Search for hearings that have a start time greater than or equal to this startTime parameter.  Default is 00:00 (midnight) on the day of the searchDate
          type: string
          required: false
        endTime:
          description: e.g. '11:30'. Search for hearings that have a start time less than or equal to this endTime parameter.  Default is '23:59:59.999999999' on the day of the searchDate
          type: string
          required: false

      responses:
            200:
                description: OK
                body:
                  application/vnd.listing.search.hearings+json:
                    example:  !include json/listing.search.hearings.json
                    schema:  !include  json/schema/listing.search.hearings.json

/hearings/available-search:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.listing.search.hearings+json
            name: listing.available.search.hearings
        ...
      queryParameters:
        hearingId:
          description: hearing id
          type: string
          required: true
        caseUrn:
          description: Comma seperated specific case urns
          type: string
          required: false
        searchCriteria:
          description: comma seperated list of search criteria. Must be at least one/both of the following values CASE_IN_HEARING, MATCHED_DEFENDANTS
          type: string
          required: false
        jurisdictionType:
           description: it one of type of jurisdictionType i.e. CROWN, MAGISTRATES
           type: string
           required: false
      responses:
            200:
                description: OK
                body:
                  application/vnd.listing.search.hearings+json:
                    example:  !include json/listing.search.hearings.json
                    schema:  !include  json/schema/listing.search.hearings.json

/hearings/range-search:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.listing.search.hearings+json
            name: listing.range.search.hearings
        ...
      queryParameters:
        allocated:
          description: true for allocated hearings, false for unallocated hearings
          type: boolean
          required: true
        courtCentreId:
          description: reference data id for the court centre
          type: string
          required: false
        courtRoomId:
          description: reference data id for the court room
          type: string
          required: false
        authorityId:
          description: reference data id for the authority code
          type: string
          required: false
        hearingTypeId:
          description: reference data id for the hearng type
          type: string
          required: false
        jurisdictionType:
          description: the jurisdiction under which the hearing is being prosecuted, for example CROWN or MAGISTRATE
          type: string
          required: false
        startDate:
          description: If not provided then startdate is defaulted to '1900-01-01'.  (hearingStartDate between startDate and endDate) or (hearingEndDate between startDate and endDate) or (hearingStartDate <= startDate and hearingEndDate >= endDate)
          type: date
          required: false
        endDate:
          description: If not provided then endDate is defaulted to '9999-01-01'.  (hearingStartDate between startDate and endDate) or (hearingEndDate between startDate and endDate) or (hearingStartDate <= startDate and hearingEndDate >= endDate)
          type: date
          required: false
        weekCommencingStartDate:
          description: (hearingWeekCommencingStartDate between weekCommencingStartDate and weekCommencingEndDate) or (hearingWeekCommencingStartDate <= weekCommencingStartDate and hearingWeekCommencingEndDate >= weekCommencingEndDate)
          type: date
          required: false
        weekCommencingEndDate:
          description: (hearingWeekCommencingEndDate between weekCommencingStartDate and weekCommencingEndDate) or (hearingWeekCommencingStartDate <= weekCommencingStartDate and hearingWeekCommencingEndDate >= weekCommencingEndDate)
          type: date
          required: false
      responses:
            200:
                description: OK
                body:
                  application/vnd.listing.search.hearings+json:
                    example:  !include json/listing.search.hearings.json
                    schema:  !include  json/schema/listing.search.hearings.json

/hearings/{id}:
  uriParameters:
    id:
      description: The ID of the Hearing; must be a valid UUID
      type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.listing.search.hearing+json
          name: listing.search.hearing
      ...
    responses:
          200:
              description: OK
              body:
                application/vnd.listing.search.hearing+json:
                  example: !include json/listing.search.hearing.json
                  schema:  !include json/schema/listing.search.hearing.json

/courtlist:
  description: get court list document
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.listing.search.court.list+json
          name: listing.search.court.list
      ...
    queryParameters:
        courtCentreId:
          description: reference data id for the court centre
          type: string
          required: true
        courtRoomId:
          description: reference data id for the court room
          type: string
          required: false
        listId:
          description: court list name to generate ( e.g. PUBLIC, STANDAND, ALPHABETICAL)
          type: string
          required: true
        startDate:
          description: hearing start date in format 'YYYY-MM-DD'.
          type: date
          required: true
        endDate:
          description: hearing end date in format 'YYYY-MM-DD'
          type: date
          required: true
        restricted:
          description: only applicable for standard courtlist. Set true to get restricted standard court list
          type: boolean
          required: false
          default: false
    responses:
      200:
        body:
          application/vnd.listing.search.court.list+json:

/courtListPublishStatus/{courtCentreId}:
  description: get status of latest publish court list document
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.listing.court.list.publish.status+json
          name: listing.court.list.publish.status
      ...
    queryParameters:
        publishCourtListTypes:
          description: publish court list types delimited by comma(,) (example FIRM,WARN)
          type: string
          required: true
        publishDate:
          description: publish date in format 'YYYY-MM-DD'
          type: date
          required: true
        weekCommencing:
          description: set true when the request is for getting the details
          type: boolean
          required: false
          default: false
    responses:
      200:
        body:
          application/vnd.listing.court.list.publish.status+json:
            example:  !include json/listing.court.list.publish.status.json
            schema:  !include  json/schema/listing.court.list.publish.status.json

/hearingSlots:
  get:
    description: |
      Retrieve available hearing slots from Azure scsl database for the given criteria
      ...
      (mapping):
          responseType: application/vnd.listing.search.hearing.slots+json
          name: listing.search.hearing.slots
      ...
    queryParameters:
        panel:
            description: panel Type ( ADULT/YOUTH/ADULT,YOUTH)
            type: string
            required: true
        sessionStartDate:
            description: startDate
            type: string
            required: true
        sessionEndDate:
            description: endDate
            type: string
            required: true
        oucodeL2Code:
            description: Operational unit
            type: string
            required: false
        ouCode:
            description: Courthouse oucode
            type: string
            required: false
        courtRoomId:
            description: courtRoomId
            type: string
            required: false
        courtRoomNumber:
            description: courtRoomNumber
            type: string
            required: false
        businessType:
            description: businessType
            type: string
            required: false
        courtSession:
            description: AM/PM/All day
            type: string
            required: false
        pageSize:
            description: Number of records to be displayed per page
            type: string
            required: true
        pageNumber:
            description: currentPageNumber details
            type: string
            required: true
    responses:
        200:
            description: OK
            body:
                application/vnd.listing.search.hearing.slots+json:
                  example:  !include json/listing.search.hearing.slots.json
                  schema:  !include  json/schema/listing.search.hearing.slots.json

/hearings/unscheduled:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.listing.search.hearings+json
            name: listing.unscheduled.search.hearings
        ...
      queryParameters:
        caseUrn:
          type: string
          required: false
        typeOfList:
          type: string
          required: false
        oucodeL2Code:
          type: string
          required: false
        courtCentreId:
          description: reference data id for the court centre
          type: string
          required: false
      responses:
            200:
                description: OK
                body:
                  application/vnd.listing.search.hearings+json:
                    example:  !include json/listing.search.hearings.json
                    schema:  !include  json/schema/listing.search.hearings.json