package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.listing.domain.RuleConstants;

import java.util.Arrays;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Query - API - listing.search.hearings"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.search.hearings");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.YOTS, RuleConstants.CPS, RuleConstants.NPS, RuleConstants.COURT_ASSOCIATE));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - listing.available.search.hearings"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.available.search.hearings");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.YOTS, RuleConstants.CPS, RuleConstants.NPS, RuleConstants.COURT_ASSOCIATE));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - listing.range.search.hearings"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.range.search.hearings");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.YOTS, RuleConstants.CPS, RuleConstants.NPS, RuleConstants.COURT_ASSOCIATE));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - listing.public.list"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.public.list");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.LEGAL_ADVISERS, RuleConstants.COURT_CLERKS, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.CROWN_COURT_ADMIN));
  then
    $outcome.setSuccess(true);
end
rule "Query - API - listing.search.court.list"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.search.court.list");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.YOTS, RuleConstants.CPS, RuleConstants.NPS));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - listing.search.hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.search.hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.COURT_CLERKS, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.LISTING_OFFICERS, RuleConstants.LEGAL_ADVISERS));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - listing.court.list.publish.status"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.court.list.publish.status");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.LISTING_OFFICERS, RuleConstants.COURT_CLERKS, RuleConstants.LEGAL_ADVISERS, RuleConstants.CROWN_COURT_ADMIN));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - listing.search.hearing.slots"
  when
    $outcome: Outcome();
    $action: Action(name == "listing.search.hearing.slots");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.COURT_CLERKS, RuleConstants.COURT_ADMINISTRATORS, RuleConstants.CROWN_COURT_ADMIN, RuleConstants.LISTING_OFFICERS, RuleConstants.LEGAL_ADVISERS));
  then
    $outcome.setSuccess(true);
end
