#%RAML 0.8
title: Listing - Command API
baseUri: http://localhost:8080/listing-command-api/command/api/rest/listing
protocols: [ HTTP, HTTPS ]

/cases:
  post:
    description: |
      List case for hearing
      ...
      (mapping):
        requestType: application/vnd.listing.command.send-case-for-listing+json
        name: listing.command.send-case-for-listing
      ...
    body:
      application/vnd.listing.command.send-case-for-listing+json:
        example: !include json/listing.command.send-case-for-listing.json
        schema: !include json/schema/listing.command.send-case-for-listing.json
    responses:
      202:
        description: Request accepted

/hearings/{hearingId}:
  post:
    description: |
      Update hearing for listing
      ...
      (mapping):
        requestType: application/vnd.listing.command.update-hearing-for-listing+json
        name: listing.command.update-hearing-for-listing
      ...
    body:
      application/vnd.listing.command.update-hearing-for-listing+json:
        example: !include json/listing.command.update-hearing-for-listing.json
        schema: !include json/schema/listing.command.update-hearing-for-listing.json
    responses:
      202:
        description: Request accepted
