#%RAML 0.8
title: Listing - Command API
baseUri: http://localhost:8080/listing-command-api/command/api/rest/listing
protocols: [ HTTP, HTTPS ]

/cases:
  post:
    description: |
      List case for hearing
      ...
      (mapping):
        requestType: application/vnd.listing.command.list-court-hearing+json
        name: listing.command.list-court-hearing
      ...
    body:
      application/vnd.listing.command.list-court-hearing+json:
        example: !include json/listing.command.list-court-hearing.json
        schema: !include json/schema/listing.command.list-court-hearing.json

    responses:
      202:
        description: Request accepted

/hearings:
  post:
    description: |
      Update hearings for a listing
      ...
      (mapping):
        requestType: application/vnd.listing.command.change-judiciary-for-hearings+json
        name: listing.command.change-judiciary-for-hearings
        (mapping):
        requestType: application/vnd.listing.command.restrict-court-list+json
        name: listing.command.restrict-court-list
      ...
    body:
      application/vnd.listing.command.change-judiciary-for-hearings+json:
        schema: !include json/schema/listing.command.change-judiciary-for-hearings.json
        example: !include json/listing.command.change-judiciary-for-hearings.json
      application/vnd.listing.command.restrict-court-list+json:
        schema: !include json/schema/listing.command.restrict-court-list.json
        example: !include json/listing.command.restrict-court-list.json

    responses:
      202:
        description: Request accepted



/hearings/{hearingId}:
  post:
    description: |
      Update hearing for listing
      ...
      (mapping):
        requestType: application/vnd.listing.command.update-hearing-for-listing+json
        name: listing.command.update-hearing-for-listing
      (mapping):
        requestType: application/vnd.listing.command.update-defendants-for-hearing+json
        name: listing.command.update-defendants-for-hearing
      (mapping):
        requestType: application/vnd.listing.command.delete-offences-for-hearing+json
        name: listing.command.delete-offences-for-hearing
      (mapping):
        requestType: application/vnd.listing.command.update-offences-for-hearing+json
        name: listing.command.update-offences-for-hearing
      (mapping):
        requestType: application/vnd.listing.command.add-offences-for-hearing+json
        name: listing.command.add-offences-for-hearing
      ...
    body:
      application/vnd.listing.command.update-hearing-for-listing+json:
        example: !include json/listing.command.update-hearing-for-listing.json
        schema: !include json/schema/listing.command.update-hearing-for-listing.json
      application/vnd.listing.command.update-defendants-for-hearing+json:
        example: !include json/listing.command.update-defendants-for-hearing.json
        schema: !include json/schema/listing.command.update-defendants-for-hearing.json
      application/vnd.listing.command.delete-offences-for-hearing+json:
        example: !include json/listing.command.delete-offences-for-hearing.json
        schema: !include json/schema/listing.command.delete-offences-for-hearing.json
      application/vnd.listing.command.add-offences-for-hearing+json:
        example: !include json/listing.command.add-offences-for-hearing.json
        schema: !include json/schema/listing.command.add-offences-for-hearing.json
      application/vnd.listing.command.update-offences-for-hearing+json:
        example: !include json/listing.command.update-offences-for-hearing.json
        schema: !include json/schema/listing.command.update-offences-for-hearing.json
    responses:
      202:
        description: Request accepted

/hearings/sequence:
  post:
    description: |
      Squence  hearings
      ...
      (mapping):
        requestType: application/vnd.listing.command.sequence-hearings+json
        name: listing.command.sequence-hearings
      ...
    body:
      application/vnd.listing.command.sequence-hearings+json:
        schema: !include json/schema/listing.command.sequence-hearings.json
        example: !include json/listing.command.sequence-hearings.json

    responses:
      202:
        description: Request accepted


/publishCourtList/{courtCentreId}:
  post:
    description: |
      Publish court list
      ...
      (mapping):
        requestType: application/vnd.listing.command.publish-court-list+json
        name: listing.command.publish-court-list
      ...
    body:
      application/vnd.listing.command.publish-court-list+json:
        schema: !include json/schema/listing.command.publish-court-list.json
        example: !include json/listing.command.publish-court-list.json

    responses:
      202:
        description: Request accepted

/publishCourtListsForCrownCourts:
   post:
      description: |
        Publish 'final' lists for all crown courts, for the next weekday.
        ...
        (mapping):
          requestType: application/vnd.listing.command.publish-court-lists-for-crown-courts+json
          name: listing.command.publish-court-lists-for-crown-courts
        ...
      body:
        application/vnd.listing.command.publish-court-lists-for-crown-courts+json:
          schema: !include json/schema/listing.command.publish-court-lists-for-crown-courts.json
          example: !include json/listing.command.publish-court-lists-for-crown-courts.json

      responses:
        202:
          description: Request accepted

/courtlist/{courtCentreId}/{publishCourtListType}/{startDate}:
   post:
      description: |
        Export court list
        ...
        (mapping):
          requestType: application/vnd.listing.command.court-list-request-export+json
          name: listing.command.court-list-request-export
        ...
      body:
        application/vnd.listing.command.court-list-request-export+json:
            schema: !include json/schema/listing.command.court-list-request-export.json
            example: !include json/listing.command.court-list-request-export.json

      responses:
        202:
          description: Request accepted
