#%RAML 0.8
title: Listing - Command API
baseUri: http://localhost:8080/listing-command-api/command/api/rest/listing
protocols: [ HTTP, HTTPS ]

/cases:
  post:
    description: |
      List case for hearing
      ...
      (mapping):
        requestType: application/vnd.listing.command.send-case-for-listing+json
        name: listing.command.send-case-for-listing
      (mapping):
        requestType: application/vnd.listing.command.update-case-defendant-details+json
        name: listing.command.update-case-defendant-details
      (mapping):
        requestType: application/vnd.listing.command.update-case-defendant-offences+json
        name: listing.command.update-case-defendant-offences
      ...
    body:
      application/vnd.listing.command.send-case-for-listing+json:
        example: !include json/listing.command.send-case-for-listing.json
        schema: !include json/schema/listing.command.send-case-for-listing.json
      application/vnd.listing.command.update-case-defendant-details+json:
        example: !include json/listing.command.update-case-defendant-details.json
        schema: !include json/schema/listing.command.update-case-defendant-details.json
      application/vnd.listing.command.update-case-defendant-offences+json:
        example: !include json/listing.command.update-case-defendant-offences.json
        schema: !include json/schema/listing.command.update-case-defendant-offences.json
    responses:
      202:
        description: Request accepted

/hearings/{hearingId}:
  post:
    description: |
      Update hearing for listing
      ...
      (mapping):
        requestType: application/vnd.listing.command.update-hearing-for-listing+json
        name: listing.command.update-hearing-for-listing
      (mapping):
        requestType: application/vnd.listing.command.update-defendants-for-hearing+json
        name: listing.command.update-defendants-for-hearing
      (mapping):
        requestType: application/vnd.listing.command.delete-offences-for-hearing+json
        name: listing.command.delete-offences-for-hearing
      (mapping):
        requestType: application/vnd.listing.command.update-offences-for-hearing+json
        name: listing.command.update-offences-for-hearing
      (mapping):
        requestType: application/vnd.listing.command.add-offences-for-hearing+json
        name: listing.command.add-offences-for-hearing
      ...
    body:
      application/vnd.listing.command.update-hearing-for-listing+json:
        example: !include json/listing.command.update-hearing-for-listing.json
        schema: !include json/schema/listing.command.update-hearing-for-listing.json
      application/vnd.listing.command.update-defendants-for-hearing+json:
        example: !include json/listing.command.update-defendants-for-hearing.json
        schema: !include json/schema/listing.command.update-defendants-for-hearing.json
      application/vnd.listing.command.delete-offences-for-hearing+json:
        example: !include json/listing.command.delete-offences-for-hearing.json
        schema: !include json/schema/listing.command.delete-offences-for-hearing.json
      application/vnd.listing.command.add-offences-for-hearing+json:
        example: !include json/listing.command.add-offences-for-hearing.json
        schema: !include json/schema/listing.command.add-offences-for-hearing.json
      application/vnd.listing.command.update-offences-for-hearing+json:
        example: !include json/listing.command.update-offences-for-hearing.json
        schema: !include json/schema/listing.command.update-offences-for-hearing.json
    responses:
      202:
        description: Request accepted
