#%RAML 0.8
title: Public events
baseUri: message://event/processor/message/listing
version: v1
/public.event:
  get:
      responses:
          200:
              body:
                application/vnd.public.listing.case-sent-for-listing+json:
                    schema: !include json/schema/public.listing.case-sent-for-listing.json
                    example: !include json/public.listing.case-sent-for-listing.json
                application/vnd.public.hearing-confirmed+json:
                    schema: !include json/schema/public.hearing-confirmed.json
                    example: !include json/public.hearing-confirmed.json
                application/vnd.public.hearing-updated+json:
                    schema: !include json/schema/public.hearing-updated.json
                    example: !include json/public.hearing-updated.json
