#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/processor/message/listing

/listing.event:
    post:
      body:
        application/vnd.listing.events.hearing-listed+json:
            schema: !include json/schema/listing.events.hearing-listed.json
            example: !include json/listing.events.hearing-listed.json
        application/vnd.listing.events.hearing-allocated-for-listing+json:
            schema: !include json/schema/listing.events.hearing-allocated-for-listing.json
            example: !include json/listing.events.hearing-allocated-for-listing.json
        application/vnd.listing.events.allocated-hearing-updated-for-listing+json:
            schema: !include json/schema/listing.events.allocated-hearing-updated-for-listing.json
            example: !include json/listing.events.allocated-hearing-updated-for-listing.json
        application/vnd.listing.events.defendants-to-be-updated+json:
            schema: !include json/schema/listing.events.defendants-to-be-updated.json
            example: !include json/listing.events.defendants-to-be-updated.json
        application/vnd.listing.events.defendants-to-be-added-for-court-proceedings+json:
            schema: !include json/schema/listing.events.defendants-to-be-added-for-court-proceedings.json
            example: !include json/listing.events.defendants-to-be-added-for-court-proceedings.json
        application/vnd.listing.events.offences-to-be-updated+json:
            schema: !include json/schema/listing.events.offences-to-be-updated.json
            example: !include json/listing.events.offences-to-be-updated.json
        application/vnd.listing.events.offences-to-be-deleted+json:
            schema: !include json/schema/listing.events.offences-to-be-deleted.json
            example: !include json/listing.events.offences-to-be-deleted.json
        application/vnd.listing.events.offences-to-be-added+json:
            schema: !include json/schema/listing.events.offences-to-be-added.json
            example: !include json/listing.events.offences-to-be-added.json
        application/vnd.listing.events.court-application-added-for-hearing+json:
            schema: !include json/schema/listing.events.court-application-added-for-hearing.json
            example: !include json/listing.events.court-application-added-for-hearing.json
        application/vnd.listing.events.court-application-to-be-updated+json:
            schema: !include json/schema/listing.events.court-application-to-be-updated.json
            example: !include json/listing.events.court-application-to-be-updated.json
        application/vnd.listing.events.court-list-restricted+json:
            schema: !include json/schema/listing.events.court-list-restricted.json
            example: !include json/listing.events.court-list-restricted.json
        application/vnd.listing.event.publish-court-list-produced+json:
            schema: !include json/schema/listing.event.publish-court-list-produced.json
            example: !include json/listing.event.publish-court-list-produced.json
        application/vnd.listing.event.publish-court-list-export-failed+json:
            schema: !include json/schema/listing.event.publish-court-list-export-failed.json
            example: !include json/listing.event.publish-court-list-export-failed.json
        application/vnd.listing.event.publish-court-list-export-successful+json:
            schema: !include json/schema/listing.event.publish-court-list-export-successful.json
            example: !include json/listing.event.publish-court-list-export-successful.json
        application/vnd.listing.event.publish-court-list-requested+json:
            schema: !include json/schema/listing.event.publish-court-list-requested.json
            example: !include json/listing.event.publish-court-list-requested.json
/public.event:
    post:
      body:

        application/vnd.public.progression.defendant-offences-changed+json:
            schema: !include json/schema/public.progression.defendant-offences-changed.json
            example: !include json/public.progression.defendant-offences-changed.json
        application/vnd.public.progression.case-defendant-changed+json:
            schema: !include json/schema/public.progression.case-defendant-changed.json
            example: !include json/public.progression.case-defendant-changed.json
        application/vnd.public.progression.court-application-changed+json:
            schema: !include json/schema/public.progression.court-application-changed.json
            example: !include json/public.progression.court-application-changed.json
        application/vnd.public.progression.events.hearing-extended+json:
            schema: !include json/schema/public.progression.events.hearing-extended.json
            example: !include json/public.progression.events.hearing-extended.json
        application/vnd.public.progression.defendants-added-to-court-proceedings+json:
            schema: !include json/schema/public.progression.defendants-added-to-court-proceedings.json
            example: !include json/public.progression.defendants-added-to-court-proceedings.json
        application/vnd.public.progression.events.case-or-application-ejected+json:
            schema: !include json/schema/public.progression.events.case-or-application-ejected.json
            example: !include json/public.progression.events.case-or-application-ejected.json
